swagger: "2.0"
info:
  description: "## pdown RESTful server APIs"
  version: "1.0.0"
  title: "pdown RESTful"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:26339"
basePath: "/"
tags:
- name: "config"
  description: "服务器配置相关"
- name: "task"
  description: "下载任务相关"
- name: "util"
  description: "工具方法"
schemes:
- "http"
paths:
  /config:
    put:
      tags:
      - "config"
      summary: "更新服务器配置信息"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/ServerConfig"
      responses:
        200:
          description: "成功"
        400:
          description: "参数错误(code=4000 参数解析错误)"
          schema:
            $ref: "#/definitions/BadRequest"
        500:
          description: "服务器异常"
    get:
      tags:
      - "config"
      summary: "获取服务器配置信息"
      responses:
        200:
          description: "成功"
          schema:
            $ref: "#/definitions/ServerConfig"
        400:
          description: "参数错误(code=4000 参数解析错误)"
          schema:
            $ref: "#/definitions/BadRequest"
        500:
          description: "服务器异常"
  /tasks:
    post:
      tags:
      - "task"
      summary: "创建下载任务"
      description: "创建成功后，如果正在下载的任务数量已满，则任务为待下载状态。如果请求里包含下载响应的大小和文件名称就不会在创建任务时额外发起一次请求去解析响应相关信息。"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/TaskCreateForm"
      responses:
        200:
          description: "创建成功后的任务相关信息"
          schema:
            $ref: "#/definitions/TaskInfoForm"
        400:
          description: "参数错误(code=4000 参数解析错误,code=4001 请求为空,code=4002 URL为空)"
          schema:
            $ref: "#/definitions/BadRequest"
        500:
          description: "服务器异常"
    get:
      tags:
      - "task"
      summary: "获取任务列表"
      responses:
        200:
          description: "success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TaskInfoForm"
        404:
          description: "任务不存在"
        500:
          description: "服务器异常"
    delete:
      tags:
      - "task"
      summary: "删除所有任务"
      parameters:
      - in: "query"
        name: "delFile"
        type: "boolean"
        default: false
        description: "是否删除已下载的文件"
      responses:
        200:
          description: "成功"
        500:
          description: "服务器异常"
  /tasks/{id}:
    delete:
      tags:
      - "task"
      summary: "删除指定任务"
      parameters:
      - in: "path"
        name: "id"
        type: "string"
        required: true
        description: "任务ID"
      - in: "query"
        name: "delFile"
        type: "boolean"
        default: false
        description: "是否删除已下载的文件"
      responses:
        200:
          description: "成功"
        404:
          description: "任务不存在"
        500:
          description: "服务器异常"
  /tasks/pause:
    put:
      tags:
      - "task"
      summary: "暂停所有任务"
      responses:
        200:
          description: "成功"
        500:
          description: "服务器异常"
  /tasks/{id}/pause:
    put:
      tags:
      - "task"
      summary: "暂停指定任务"
      parameters:
      - in: "path"
        name: "id"
        type: "string"
        required: true
        description: "任务ID"
      responses:
        200:
          description: "成功"
        404:
          description: "任务不存在"
        500:
          description: "服务器异常"
  /tasks/resume:
    put:
      tags:
      - "task"
      summary: "恢复所有任务"
      responses:
        200:
          description: "成功"
          schema:
            $ref: "#/definitions/ResumeVo"
        500:
          description: "服务器异常"
  /tasks/{id}/resume:
    put:
      tags:
      - "task"
      summary: "恢复指定任务"
      parameters:
      - in: "path"
        name: "id"
        type: "string"
        required: true
        description: "任务ID"
      responses:
        200:
          description: "成功"
          schema:
            $ref: "#/definitions/ResumeVo"
        404:
          description: "任务不存在"
        500:
          description: "服务器异常"
  /tasks/progress:
    get:
      tags:
      - "task"
      summary: "获取指定任务的下载进度"
      parameters:
      - in: "query"
        name: "ids"
        type: "array"
        items:
          type: "string"
        collectionFormat: "csv"
        required: true
        description: "任务ID列表,多个用,隔开"
      responses:
        200:
          description: "成功"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TaskInfoForm"
        404:
          description: "任务不存在"
        500:
          description: "服务器异常"
  /util/resolve:
    put:
      tags:
      - "util"
      summary: "解析请求,获取响应的大小和文件名以及是否支持断点下载"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/RequestForm"
      responses:
        200:
          description: "成功"
          schema:
              $ref: "#/definitions/ResponseForm"
        400:
          description: "参数错误(code=4000 参数解析错误,code=4001 URL为空)"
          schema:
            $ref: "#/definitions/BadRequest"
        500:
          description: "服务器异常"
definitions:
  ServerConfig:
    type: "object"
    properties:
      filePath:
        type: "string"
        description: "默认下载路径."
      connections:
        type: "integer"
        format: "int32"
        description: "任务下载HTTP连接数."
      timeout:
        type: "integer"
        format: "int32(S)"
        description: "当一段时间内没有响应，将会自动重试."
      retryCount:
        type: "integer"
        format: "int32"
        description: "单个连接最大失败重试次数，当所有连接的失败次数都超出时，任务将停止下载并标记为失败."
      speedLimit:
        type: "integer"
        format: "int64(B/S)"
        description: "单个任务最大下载速度限制."
      autoRename:
        type: "boolean"
        description: "当下载目录出现重名文件时是否自动重命名，当为false时出现重名文件的情况任务会创建失败."
      port:
        type: "integer"
        format: "int32"
        description: "服务器端口，默认为26339。"
      taskLimit:
        type: "integer"
        format: "int32"
        description: "最大同时下载的任务数量。"
      totalSpeedLimit:
        type: "integer"
        format: "int64(B/S)"
        description: "全局下载速度限制。"
      proxyConfig:
        type: "object"
        description: "二级代理设置"
        properties:
          proxyType:
            type: "string"
            description: "代理服务器类型"
            default: "HTTP"
            enum:
            - "HTTP"
            - "SOCKS4"
            - "SOCKS5"
          host:
            type: "string"
            description: "代理服务器地址"
          port:
            type: "integer"
            format: "int32"
            description: "代理服务器端口号"
          user:
            type: "string"
            description: "代理服务器验证用户名"
          pwd:
            type: "string"
            description: "代理服务器验证密码"
  TaskCreateForm:
    type: "object"
    properties:
      request:
        $ref: "#/definitions/RequestForm"
      response:
        $ref: "#/definitions/ResponseForm"
      config:
        $ref: "#/definitions/ConfigForm"
  ResumeVo:
    type: "object"
    properties:
      pauseIds:
        type: "array"
        description: "暂停的任务ID列表."
        items:
          type: "string"
      resumeIds:
        type: "array"
        description: "恢复的任务ID列表."
        items:
          type: "string"
  TaskInfoForm:
    type: "object"
    properties:
      id:
        type: "string"
        description: "任务ID."
      request:
        $ref: "#/definitions/RequestForm"
      response:
        $ref: "#/definitions/ResponseForm"
      config:
        $ref: "#/definitions/ConfigForm"
      info:
        type: "object"
        description: "任务下载进度信息"
        properties:
          downSize:
            type: "integer"
            format: "int64"
          startTime:
            type: "integer"
            format: "int64"
          lastStartTime:
            type: "integer"
            format: "int64"
          status:
            type: "integer"
            format: "int32"
          speed:
            type: "integer"
            format: "int64"
          chunkInfoList:
            type: "array"
            items:
                type: "object"
                properties:
                  index:
                    type: "integer"
                    format: "int32"
                  downSize:
                    type: "integer"
                    format: "int64"
                  totalSize:
                    type: "integer"
                    format: "int64"
                  lastCountSize:
                    type: "integer"
                    format: "int64"
                  lastPauseTime:
                    type: "integer"
                    format: "int64"
                  pauseTime:
                    type: "integer"
                    format: "int64"
                  status:
                    type: "integer"
                    format: "int32"
                  speed:
                    type: "integer"
                    format: "int64"
          connectInfoList:
            type: "array"
            items:
                type: "object"
                properties:
                  startPosition:
                    type: "integer"
                    format: "int64"
                  endPosition:
                    type: "integer"
                    format: "int64"
                  downSize:
                    type: "integer"
                    format: "int64"
                  errorCount:
                    type: "integer"
                    format: "int32"
                  chunkIndex:
                    type: "integer"
                    format: "int32"
                  status:
                    type: "integer"
                    format: "int32"
  RequestForm:
    type: "object"
    description: "下载请求信息"
    properties:
      url:
        type: "string"
        description: "请求URL"
      heads:
        type: "object"
        description: "请求头，示例：{\"User-Agent:\",\"Chrome\"}"
        format: "{key:value}"
      body:
        type: "string"
        description: "请求体，仅支持文本内容"
  ResponseForm:
    type: "object"
    description: "下载响应信息,如果知道响应的大小和文件名，则可以省去一次解析响应相关信息的请求"
    properties:
      fileName:
        type: "string"
        description: "文件名"
      totalSize:
        type: "integer"
        description: "响应大小"
        format: "int64(B)"
      supportRange:
        type: "boolean"
        description: "是否支持断点下载"
  ConfigForm:
    type: "object"
    description: "下载相关配置"
    properties:
      filePath:
          type: "string"
          description: "下载目录"
      connections:
        type: "integer"
        description: "连接数(当不支持断点下载时，该参数不生效，连接数为1)"
        format: "int32"
      timeout:
        type: "integer"
        description: "当一段时间内没有响应，将会自动重试."
        format: "int32(S)"
      retryCount:
        type: "integer"
        description: "单个连接最大失败重试次数，当所有连接的失败次数都超出时，任务将停止下载并标记为失败."
        format: "int32"
      autoRename:
        type: "boolean"
        description: "当下载目录出现重名文件时是否自动重命名，当为false时出现重名文件的情况任务会创建失败."
  BadRequest:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"